### ISSUE TITLE
backtest

### ISSUE THREAD

**Issue by gibo** [robertmartin8/MachineLearningStocks#15]
I would like to contribute to this project and have read through the readme in detail.

I have noticed you speak about a fatal flaw in the backtest, what is it? I can work on this and submit a PR.

**Comment by robertmartin8** [comment]
Hi,

In a sense, this project is "designed" to be flawed, or at least I have implemented the simplest possible solution fully aware of the problems. However, I'm inclined to leave it as it stands for anyone who wants to use this project as a starting block. 

Robert

**Comment by gibo** [comment]
understood.

do you have any hint of what the problem is? This is my first go at ML applied to finance.

**Comment by robertmartin8** [comment]
Try to think about what a backtest really should be doing. It is meant to see how a strategy would have performed in the past – it should tell you what your performance would have been if you had this code 5 years ago.  

However, if you look at [backtesting.py](https://github.com/robertmartin8/MachineLearningStocks/blob/master/backtesting.py), you'll see that there are some parts of the methodology that you could *not* have reproduced 5 years ago, meaning that the backtest is flawed. 

As a tangible hint, the flaw is introduced in the first half of the backtesting file. Let me know if you'd like more guidance, but I really think it would be very useful to mull over this problem. 

Robert

**Comment by gibo** [comment]
that's enough for me to get going.. and agree i would prefer to solve the problem on my own.

**Comment by gibo** [comment]
Ok, after numerous train rides mulling it over I think I have the problem.

Presume the issue is that you are training the model on future data, yet making predictions for some stocks in the past?

So seems the solution would be to:
- randomly select the year you'd like to predict
- ensure the training test split is only run on years prior  

(I can delete my comment if you want)

**Comment by robertmartin8** [comment]
@gibo I've dropped you an email (found on your github profile), if that's ok.

**Comment by gibo** [comment]
.
