### ISSUE TITLE
intraQuarter/_KeyStats/ issue

### ISSUE THREAD

**Issue by heisenbergwong** [robertmartin8/MachineLearningStocks#16]
Hi Robert, I noticed the intraQuarter/_KeyStats/ data is used,but I cannot find it,could u tell me where it is or  
how I can get it?thx so much!

**Comment by robertmartin8** [comment]
Hi,

As stated in the readme, the data is available externally at [this link](https://pythonprogramming.net/data-acquisition-machine-learning/).

Robert
