### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by vinaykd25** [robertmartin8/MachineLearningStocks#19]
There is error zero-sized array to reduction operation maximum which has no identity
in download_historical_prices.py

**Comment by robertmartin8** [comment]
Can I check that you've done the following:

- Updated all your dependencies with `pip install -r requirements.txt`
- Using python 3.6
- Followed the [instructions](https://github.com/robertmartin8/MachineLearningStocks#historical-data) regarding historical data.

If you still get the same error, please paste it here and we'll try to figure out what's wrong :)

Robert

**Comment by robertmartin8** [comment]
Closing for now, please let me know if it's still a problem
