### ISSUE TITLE
keystats.csv

### ISSUE THREAD

**Issue by boatmeup** [robertmartin8/MachineLearningStocks#21]
Hello, when I run command python parsing_keystats.py, keystats.cvs is created, but it's empty(except for the Date, unix, ticker and etc.). I know for sure that stock prices are downloaded and updates as I change date to present. Please can you help me as I tried everything to solve this.

**Comment by robertmartin8** [comment]
Hi,

Could I check whether you've [downloaded `intraQuarter`](https://github.com/robertmartin8/MachineLearningStocks#historical-stock-fundamentals)?

Robert

**Comment by boatmeup** [comment]
Hi sorry, I have sort it, it was due to 3.5 python version,  I fixed strings but still didn't run. I have update it now works smoothly. Sorry and thanks
