### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [robertmartin8/MachineLearningStocks#22]
Hello. Is it possible to integrate this with NASDAQ/IQ Option?

**Comment by robertmartin8** [comment]
Sorry for the late reply, I've been quite busy with university :) 

Could you elaborate on what you mean?

**Comment by ghost** [comment]
How to connect it to an exchange for some real trading?

**Comment by robertmartin8** [comment]
Ah, the easiest way to do that would be the [Interactive Brokers API](https://interactivebrokers.github.io/tws-api/introduction.html). But as this is an educational project I would strongly advise against that unless one makes heavy modifications and conducts rigorous backtests (even then, at your own risk!)
