### ISSUE TITLE
SET (help wanted - can't find label )

### ISSUE THREAD

**Issue by carlgoodier** [robertmartin8/MachineLearningStocks#23]
Was really impressed with this file. Most just look at historical price, but love what you have done with including a deeper assessment of the company.

I live in Bangkok and follow the Thai market. I can already get Thai historical prices, but how to change S&P500 to SET ( In yahoo I thought it would be SET.bk ( as stocks are .bk ), but does not work 

Thanks 

-

**Comment by robertmartin8** [comment]
Sorry, might not be able to help you with this one. 

Data availability is a real problem even with Western markets' stocks, so I think it would be quite difficult to find a high quality source for the Thai markets.
