### ISSUE TITLE
"from utils import data_string_to_float" import error

### ISSUE THREAD

**Issue by emskiphoto** [robertmartin8/MachineLearningStocks#24]
could not successfully import  "from utils import data_string_to_float", seemed to work after replacing with:

import utils

**Comment by emskiphoto** [comment]
The error above occurs on Jupyter Notebook.  The script runs fine as is in the IDLE/Python shell.     Using utils version 0.9.0

**Comment by robertmartin8** [comment]
Hm I haven't tested it with jupyter notebooks, is `utils.py` definitely in the same directory as your `ipynb` file?

**Comment by robertmartin8** [comment]
Closing for now. Please let me know if it needs to be reopened
