### ISSUE TITLE
Backtesting issue

### ISSUE THREAD

**Issue by maxbeyer1** [robertmartin8/MachineLearningStocks#26]
Interested in this project and possibly working on it more. Just starting out with ML but I was curious to try and figure out the issue with the backtesting. From what I can tell it is that you are training the model on future data but then making predictions for stocks in the past... 

It seems like the solution would be to first, randomly select the year you'd like to predict and then ensure the spit for both training and test is only run on years before that. Just wanted to check and see if I'm right about at least the issue. Feel free to drop me an email (on my profile) if you'd rather talk there, I know you said you want to let other people try and figure it out.

**Comment by robertmartin8** [comment]
Yeap, that's correct!
