### ISSUE TITLE
Benchmark data

### ISSUE THREAD

**Issue by lefig** [robertmartin8/MachineLearningStocks#34]
Hi Robert,

I was reviewing your most excellent work earlier and was wondering..

What index did you use to generate the sp500_index.csv data?

Was this S&P 500 (^GSPC) and did you preprocess or scale this data.

The reason I ask is that the data in the 200-207 range looks on the low side.

Thanks!

Fig

**Comment by robertmartin8** [comment]
Hi Fig,

Sorry for the late reply! I've been very busy with school. I used yahoo finance GSPC adjusted close, which can be found [here](https://finance.yahoo.com/quote/%5EGSPC/history?p=%5EGSPC).

Hope that answers your question!

Best,
Robert
